### PR TITLE
Argocd versions

### PR DESCRIPTION
**Pull request by arnouthoebreckx**
#### :heavy_check_mark: Checklist

- [ x ] Added tests for new functionality and regression tests for bug fixes
- [ ? ] Added changeset (run `yarn changeset` in the root)
- [ x ] Screenshots of before and after attached (for UI changes)
- [ x ] Added or updated documentation (if applicable)

This is a proposal for #809 

Decided to KISS and embedded the new values inside the AppDetails model as this made integrating into the existing table a lot easier. Implemented a feature flag for this feature, so that people do not have empty columns in their application.

image

### CODE REVIEW

**Comment by kissmikijr** [comment]
Thank you for this! The build is failing on a formatting problem, can you run prettier on the changes please and can you please run `yarn changeset` inside the root of the repo ? I think a minor version bump will be enough for this. These just quickly looking at it I'll get back to you with a full review.

**Comment by arnouthoebreckx** [comment]
Fixed it + added changeset

**Comment by arnouthoebreckx** [comment]
Updated the e2e tests + added some error handling for the managed-resources call, from personal experience when you use label-selector to get multiple ArgoCD applications for a single component and you have an unstable ArgoCD running (was heavily under-provisioned in resources) it could cause one of the managed-resources calls to return 500. 
In my opinion this should not block the rendering of the component.

**Comment by kissmikijr** [comment]
I'll close this for now. Feel free to reopen when you'll get time to finish it!

**Pull request closed without merging**
