### PR TITLE
Feature/filter activity stream by component

### PR DESCRIPTION
**Pull request by ivangonzalezacuna**
As requested in this issue: https://github.com/RoadieHQ/roadie-backstage-plugins/issues/183, when the annotation `jira/component` is defined, the Activity Stream does not filter the activities at all. However, I found a workaround to make that work.

If your JIRA instance has a filter by `issue-key`, then you can requests the changes by ticket or list of tickets.

If the component annotation is not present, then the code is going to be executed exactly in the same way as it was before, but if the component is defined, then the way of counting the issue types and to fetch the activity stream will be slightly different. First of all, the issue type will now return some data (just the `key` and the `issuetype` in order to reduce the amount of processed data) and use a pagination approach. Then, with a `reduce()`, the `IssueCounter` will be generated, and a list of `ticketIds` will be also returned. That list will be then used to fetch the activity stream, instead of the `projectKey`.

Finally, I've added another parameter to the config called `confluenceActivityFilter`, which allows you to filter out from the activity stream the events that happened in confluence and the component is also defined. Apparently the filtering is showing also the entries without `issue-key`, so filtering out all those activities solve that issue. It's described in the README.md how to obtain the key to test it.

I have tested it and it's working as expected. Let me know if you like this solution :smile: 

#### :heavy_check_mark: Checklist

- [x] Added tests for new functionality and regression tests for bug fixes
- [x] Added changeset (run `yarn changeset` in the root)
- [ ] Screenshots of before and after attached (for UI changes)
- [x] Added or updated documentation (if applicable)

### CODE REVIEW

**Comment by ivangonzalezacuna** [comment]
I'm not sure what failed in the `e2e-tests` pipeline. The tests locally are working fine without errors. I'm on node v16.14.2

**Comment by kissmikijr** [comment]
@ivangonzalezacuna it seems that the cypress test failed for the jira plugin. You can run It the following way locally.
- Start the example app with `yarn dev` in the root folder. 
- cd into the `packages/app` and then run yarn `cy:dev`

I can take a look a little bit later if you'll still need some help with it!

**Comment by ivangonzalezacuna** [comment]
@kissmikijr I have been able to fix one of the issues, but it's still failing. As far as I can tell right now, the intercept of the `activitystream.xml` is failing because the wait returns a timeout error. I tried to open the URL on my browser and I got the expected xml file, so I'm not sure what is going wrong with the test. I haven't worked that much with cypress, so it would be great if you can also give it a check when you get some free time for that.

**Comment by ivangonzalezacuna** [comment]
Hi @kissmikijr , finally solved the problem with the Cypress tests. Now it's ready :smile:

**Review by kissmikijr — APPROVED** [review]
Thanks, this looks good!

**Pull request merged**
