### PR TITLE
chore(bump): bump package versions

### PR DESCRIPTION
**Pull request by kuangp**
Bumping package versions to release updates to plugins from this change: https://github.com/RoadieHQ/roadie-backstage-plugins/commit/e56b75d9a131c353695e8e561c48f52dda8aee2a

### CODE REVIEW

**Comment by martina-if** [comment]
https://app.clubhouse.io/larder/story/3535

**Comment by alexcurtin** [comment]
I think this may be related to https://github.com/RoadieHQ/roadie-backstage-plugins/issues/147

Which is causing issues with `yarn backstage-cli versions:check --fix` in backstage apps.

**Comment by kuangp** [comment]
@punkle saw that you merged a fix for the CI, just rebased this change to apply that fix here as well

**Review by punkle — APPROVED** [review]

**Comment by punkle** [comment]
Thank you @kuangp, Ive merged this now.

**Comment by alexcurtin** [comment]
@punkle does that mean 1.0.13 is released with updated backstage core-components/deps?

**Comment by punkle** [comment]
@alexcurtin we are having a little trouble with the release pipeline, but are working on a fix.

**Comment by iain-b** [comment]
Fixed

**Comment by punkle** [comment]
@alexcurtin if you are referring to the roadiehq/backstage-plugin-github-pull-requests package. Version 1.0.13 of it depends on ^0.3.0 of backstage/core-components. Is that what you are looking for? I can see that the latest available version is 0.3.1. We can look at bumping that dep too if it helps?

**Comment by punkle** [comment]
Thanks for the fix @iain-b

**Comment by punkle** [comment]
@alexcurtin I created this pull request to uptake the latest core components. https://github.com/RoadieHQ/roadie-backstage-plugins/pull/163

**Comment by alexcurtin** [comment]
@punkle great thanks, I don't see `1.0.13` of the github pull request plugin available on npmjs, are you still ironing out the publish issue?

**Comment by punkle** [comment]
https://www.npmjs.com/package/@roadiehq/backstage-plugin-github-pull-requests

**Comment by punkle** [comment]
I see it at that link. Are you seeing it there?

**Comment by alexcurtin** [comment]
@punkle now i do, yep and backstage is happy - thanks for the fix!

**Pull request merged**
