### PR TITLE
feat: use fetchApi core plugin for Buildkite API client

### PR DESCRIPTION
**Pull request by knksmith57**
#### :heavy_check_mark: Checklist

- [ ] Added tests for new functionality and regression tests for bug fixes
- [ ] Added changeset (run `yarn changeset` in the root)
- [ ] Screenshots of before and after attached (for UI changes)
- [ ] Added or updated documentation (if applicable)

### CODE REVIEW

**Comment by knksmith57** [comment]
@alecjacobs5401 and I are pretty sure this will make the frontend client behave and properly attach authentication to the `fetch()` calls made to `/proxy`. this is probably busted for anyone currently gating backend plugins with auth (like us)

**Comment by kissmikijr** [comment]
Nice spot! Yes it shouldn't work at the current state thanks for this PR.  

Could you pls add a changeset? 
in the root of the repo run:
```bash
yarn changeset
```
I think a patch bump should be good for this one.

And regarding the CI tsc failed because you'll need to add the new dependency in the test also. You should be able to get a   `MockFetchApi` from the `@backstage/test-utils package`

**Comment by knksmith57** [comment]
Thank you for the quick response!

My teammate, @alecjacobs5401, is going to pick this up for us and address your feedback 🙏

**Comment by alecjacobs5401** [comment]
Hey @kissmikijr - made the requested changes you suggested!

**Review by kissmikijr — APPROVED** [review]

**Comment by kissmikijr** [comment]
Thank you for this work!

**Pull request merged**
