### PR TITLE
Added optional configuration of deadlines/due dates to Dependabot Widget

### PR DESCRIPTION
**Pull request by jrtaylorJH**
Added the ability to display deadlines for each severity level of dependabot alert in the table.

I'm a new contributor and relatively new to Backstage plugin development overall, so I'm not entirely familiar with all the procedures here. Please let me know if I've missed anything.

WIP: Add tests

#### :heavy_check_mark: Checklist

- [ ] Added tests for new functionality and regression tests for bug fixes
- [x] Added changeset (run `yarn changeset` in the root)
- [x] Screenshots of before and after attached (for UI changes)
- [x] Added or updated documentation (if applicable)

### CODE REVIEW

**Comment by jrtaylorJH** [comment]
Before
After

**Comment by jrtaylorJH** [comment]
Went ahead and moved to ready for review - haven't looked at tests in JS yet so I'll try today and see if it's actually important to add for this change. Otherwise code is mostly complete, might get refactored a bit so the changes I made are more functionalized and stand a bit separate from the main code path

**Review by Xantier — APPROVED** [review]
Looking like a good addition and as far as I can see, it's backwards compatible as well. Thanks!

**Comment by Xantier** [comment]
Few test failures before we can get this merged.

**Comment by jrtaylorJH** [comment]
Thanks for the review - I got pulled onto some other stuff but I will attempt to get these tests fixed in the coming week

**Pull request closed without merging**
