### PR TITLE
[SC-5815] polish readmes

### PR DESCRIPTION
**Pull request by kissmikijr**
Restructure and fix the plugin readmes to build on the same schema and fix broken stuff in it

- Fix broken images
- Fix features list where it was missing
- Remove migration notices
- Fix discord invite link, created one that does not expire
- Remove further instructions links

### CODE REVIEW

**Review by dtuite — DISMISSED** [review]
I didn't go through each and every README to review, but this certainly looks like an improvement to me.

**Comment by Irma12** [comment]
Make sure to include changesets :) @kissmikijr

**Comment by kissmikijr** [comment]
@Irma12 I intentionally left out the changeset, we are not changing the libraries, I don't think we should publish a new version. These changes only for the repository itself. wdyt?

**Comment by Irma12** [comment]
> @Irma12 I intentionally left out the changeset, we are not changing the libraries, I don't think we should publish a new version. These changes only for the repository itself. wdyt?

README files are shown on npm, so I think we should definitely publish them

**Comment by kissmikijr** [comment]
Ah, yea in this case we definitely should! I tottaly missed this!:) Let me create one quickly

**Review by Irma12 — APPROVED** [review]
Looks 👍 good work :)

**Pull request merged**
