### PR TITLE
docs: update readme for scaffolder argo action

### PR DESCRIPTION
**Pull request by karlhaworth**
docs: update readme for scaffolder argo action

#### :heavy_check_mark: Checklist

- [ ] Added tests for new functionality and regression tests for bug fixes
- [ ] Added changeset (run `yarn changeset` in the root)
- [ ] Screenshots of before and after attached (for UI changes)
- [X] Added or updated documentation (if applicable)

### CODE REVIEW

**Comment by karlhaworth** [comment]
Do I need a changeset if I'm just updating a README?

**Comment by Xantier** [comment]
> Do I need a changeset if I'm just updating a README?

The contents of the README are exposed in npmjs.org from the released version so probably good to bump a patch so those are then up to date as well.

**Comment by karlhaworth** [comment]
> > Do I need a changeset if I'm just updating a README?
> 
> The contents of the README are exposed in npmjs.org from the released version so probably good to bump a patch so those are then up to date as well.

Thanks. updated.

**Review by Xantier — APPROVED** [review]
Thanks Karl! Shipping.

**Pull request merged**
