### PR TITLE
update imports for `@backstage/catalog-model`

### PR DESCRIPTION
**Pull request by karlhaworth**
update imports for `@backstage/catalog-model`

remove deprecated imports in favor of new modules
  parseLocationReference -> parseLocationRef
  LOCATION_ANNOTATION -> ANNOTATION_LOCATION
  SOURCE_LOCATION_ANNOTATION -> ANNOTATION_SOURCE_LOCATION

#### :heavy_check_mark: Checklist

- [ ] Added tests for new functionality and regression tests for bug fixes
- [ ] Screenshots of before and after attached (for UI changes)
- [ ] Added or updated documentation (if applicable)

### CODE REVIEW

**Review by Xantier — COMMENTED** [review]
Thanks! 
This looks good to me. Could you add a patch changeset and we can ship this then.

**Comment by karlhaworth** [comment]
> Thanks! 
> 
> This looks good to me. Could you add a patch changeset and we can ship this then.

Will do in a bit. I missed that contributing guideline. Apologies.

**Comment by karlhaworth** [comment]
@Xantier Changeset added.

Found this also seems to fix a warning that has been coming up while upgrading.

```
[ui] WARNING in ../../node_modules/@roadiehq/backstage-plugin-github-insights/node_modules/@backstage/plugin-catalog-react/dist/index.esm.js 367:12-30
[ui] export 'serializeEntityRef' (imported as 'serializeEntityRef') was not found in '@backstage/catalog-model' (possible exports: ANNOTATION_EDIT_URL, ANNOTATION_LOCATION, ANNOTATION_ORIGIN_LOCATION, ANNOTATION_SOURCE_LOCATION, ANNOTATION_VIEW_URL, CommonValidatorFunctions, DEFAULT_NAMESPACE, DefaultNamespaceEntityPolicy, EDIT_URL_ANNOTATION, ENTITY_DEFAULT_NAMESPACE, ENTITY_META_GENERATED_FIELDS, EntityPolicies, FieldFormatEntityPolicy, KubernetesValidatorFunctions, LOCATION_ANNOTATION, NoForeignRootFieldsEntityPolicy, ORIGIN_LOCATION_ANNOTATION, RELATION_API_CONSUMED_BY, RELATION_API_PROVIDED_BY, RELATION_CHILD_OF, RELATION_CONSUMES_API, RELATION_DEPENDENCY_OF, RELATION_DEPENDS_ON, RELATION_HAS_MEMBER, RELATION_HAS_PART, RELATION_MEMBER_OF, RELATION_OWNED_BY, RELATION_OWNER_OF, RELATION_PARENT_OF, RELATION_PART_OF, RELATION_PROVIDES_API, SOURCE_LOCATION_ANNOTATION, SchemaValidEntityPolicy, VIEW_URL_ANNOTATION, apiEntityV1alpha1Validator, compareEntityToRef, componentEntityV1alpha1Validator, domainEntityV1alpha1Validator, entityEnvelopeSchemaValidator, entityHasChanges, entityKindSchemaValidator, entitySchemaValidator, generateEntityEtag, generateEntityUid, generateUpdatedEntity, getEntityName, getEntitySourceLocation, groupEntityV1alpha1Validator, locationEntityV1alpha1Validator, makeValidator, parseEntityName, parseEntityRef, parseLocationRef, parseLocationReference, resourceEntityV1alpha1Validator, stringifyEntityRef, stringifyLocationRef, stringifyLocationReference, systemEntityV1alpha1Validator, userEntityV1alpha1Validator)
[ui] 
[ui] WARNING in ../../node_modules/@roadiehq/backstage-plugin-github-pull-requests/node_modules/@backstage/plugin-catalog-react/dist/index.esm.js 367:12-30
[ui] export 'serializeEntityRef' (imported as 'serializeEntityRef') was not found in '@backstage/catalog-model' (possible exports: ANNOTATION_EDIT_URL, ANNOTATION_LOCATION, ANNOTATION_ORIGIN_LOCATION, ANNOTATION_SOURCE_LOCATION, ANNOTATION_VIEW_URL, CommonValidatorFunctions, DEFAULT_NAMESPACE, DefaultNamespaceEntityPolicy, EDIT_URL_ANNOTATION, ENTITY_DEFAULT_NAMESPACE, ENTITY_META_GENERATED_FIELDS, EntityPolicies, FieldFormatEntityPolicy, KubernetesValidatorFunctions, LOCATION_ANNOTATION, NoForeignRootFieldsEntityPolicy, ORIGIN_LOCATION_ANNOTATION, RELATION_API_CONSUMED_BY, RELATION_API_PROVIDED_BY, RELATION_CHILD_OF, RELATION_CONSUMES_API, RELATION_DEPENDENCY_OF, RELATION_DEPENDS_ON, RELATION_HAS_MEMBER, RELATION_HAS_PART, RELATION_MEMBER_OF, RELATION_OWNED_BY, RELATION_OWNER_OF, RELATION_PARENT_OF, RELATION_PART_OF, RELATION_PROVIDES_API, SOURCE_LOCATION_ANNOTATION, SchemaValidEntityPolicy, VIEW_URL_ANNOTATION, apiEntityV1alpha1Validator, compareEntityToRef, componentEntityV1alpha1Validator, domainEntityV1alpha1Validator, entityEnvelopeSchemaValidator, entityHasChanges, entityKindSchemaValidator, entitySchemaValidator, generateEntityEtag, generateEntityUid, generateUpdatedEntity, getEntityName, getEntitySourceLocation, groupEntityV1alpha1Validator, locationEntityV1alpha1Validator, makeValidator, parseEntityName, parseEntityRef, parseLocationRef, parseLocationReference, resourceEntityV1alpha1Validator, stringifyEntityRef, stringifyLocationRef, stringifyLocationReference, systemEntityV1alpha1Validator, userEntityV1alpha1Validator)
[ui] 
[ui] WARNING in ../../node_modules/@roadiehq/backstage-plugin-security-insights/node_modules/@backstage/plugin-catalog-react/dist/index.esm.js 367:12-30
[ui] export 'serializeEntityRef' (imported as 'serializeEntityRef') was not found in '@backstage/catalog-model' (possible exports: ANNOTATION_EDIT_URL, ANNOTATION_LOCATION, ANNOTATION_ORIGIN_LOCATION, ANNOTATION_SOURCE_LOCATION, ANNOTATION_VIEW_URL, CommonValidatorFunctions, DEFAULT_NAMESPACE, DefaultNamespaceEntityPolicy, EDIT_URL_ANNOTATION, ENTITY_DEFAULT_NAMESPACE, ENTITY_META_GENERATED_FIELDS, EntityPolicies, FieldFormatEntityPolicy, KubernetesValidatorFunctions, LOCATION_ANNOTATION, NoForeignRootFieldsEntityPolicy, ORIGIN_LOCATION_ANNOTATION, RELATION_API_CONSUMED_BY, RELATION_API_PROVIDED_BY, RELATION_CHILD_OF, RELATION_CONSUMES_API, RELATION_DEPENDENCY_OF, RELATION_DEPENDS_ON, RELATION_HAS_MEMBER, RELATION_HAS_PART, RELATION_MEMBER_OF, RELATION_OWNED_BY, RELATION_OWNER_OF, RELATION_PARENT_OF, RELATION_PART_OF, RELATION_PROVIDES_API, SOURCE_LOCATION_ANNOTATION, SchemaValidEntityPolicy, VIEW_URL_ANNOTATION, apiEntityV1alpha1Validator, compareEntityToRef, componentEntityV1alpha1Validator, domainEntityV1alpha1Validator, entityEnvelopeSchemaValidator, entityHasChanges, entityKindSchemaValidator, entitySchemaValidator, generateEntityEtag, generateEntityUid, generateUpdatedEntity, getEntityName, getEntitySourceLocation, groupEntityV1alpha1Validator, locationEntityV1alpha1Validator, makeValidator, parseEntityName, parseEntityRef, parseLocationRef, parseLocationReference, resourceEntityV1alpha1Validator, stringifyEntityRef, stringifyLocationRef, stringifyLocationReference, systemEntityV1alpha1Validator, userEntityV1alpha1Validator)
[ui] 
[ui] webpack compiled with 3 warnings
```

image

**Comment by Xantier** [comment]
Excellent. This looks good so I'll merge this in and release. Thanks @karlhaworth

**Pull request merged**
