### PR TITLE
Allow to hide issue filter by configuration

### PR DESCRIPTION
**Pull request by stephane-mori**
#### :heavy_check_mark: Checklist

- [x] Added tests for new functionality and regression tests for bug fixes
- [x] Added changeset (run `yarn changeset` in the root)
- [x] Screenshots of before and after attached (for UI changes)
- [ ] Added or updated documentation (if applicable)

### CODE REVIEW

**Comment by stephane-mori** [comment]
Linked to issue : https://github.com/RoadieHQ/roadie-backstage-plugins/issues/996

**Comment by kissmikijr** [comment]
Can you please provide  before|after pictures?

**Comment by stephane-mori** [comment]
after
before

**Comment by kissmikijr** [comment]
I'm a bit puzzled by this introducing this would start a pattern where potentially we could be asked why we decided to support some kind of frontend rendering based on the app-config configuration which I'm not a big fan of. Can you please elaborate on why are you trying to remove this? Do you have a use case where people got confused by how it works? Tbh I don't think it hurts that it is there it's not required to use it.

**Comment by stephane-mori** [comment]
The linked jira workflow configuration is very complicated and states on this filter are hard to apprehend. That's why I want to provide a patch hide this filter by configuration.

Do you prefer an other way than app-config configuration to configure this need ?
I want this filter dissapear. I prefer configuration way, but if isn't possible, i will have to fork.

**Comment by kissmikijr** [comment]
My problem is the configuration via the app-config.yaml. I'd prefer if this would be a regular prop setting on the JiraCard so when you implement it in your backstage you could just say <JiraCard filter={false}/>

**Comment by stephane-mori** [comment]
I don't know how to add a commit to this PR.
I just created another PR .... https://github.com/RoadieHQ/roadie-backstage-plugins/pull/1035

**Comment by stephane-mori** [comment]
Done !

https://github.com/RoadieHQ/roadie-backstage-plugins/pull/997/commits/3e9dab9d83af70f566b5c3d6d6eef7e1c95f3be1

**Review by kissmikijr — APPROVED** [review]
Thank you! This is exactly what I was thinking!

**Pull request merged**
