### PR TITLE
Add FE system support for the Argocd plugin

### PR DESCRIPTION
**Pull request by nuritizra**
This PR adds support for the [new frontend system](https://backstage.io/docs/frontend-system/) to the Argocd plugin by exposing entity cards and the API as extensions under the '/alpha' subpath. This change is fully back-compatible / has no effect on consumers who are still using the standard frontend system.

Spotify will be updating OSS plugins to the new frontend & backend as we work towards an updated Backstage plugin framework. We're prioritizing some community favorites first, and the Spotify team will help manage any unintentional issues that arise.

#### :heavy_check_mark: Checklist

- [X] Added tests for new functionality and regression tests for bug fixes
- [X] Added changeset (run `yarn changeset` in the root)
- [ ] Screenshots of before and after attached (for UI changes)
- [ ] Added or updated documentation (if applicable)

### CODE REVIEW

**Comment by nuritizra** [comment]
@karlhaworth appriciate your review!

**Comment by karlhaworth** [comment]
Apologies for the delay. I’ll try to get a team member on this, this week. Thank you.

**Review by aharken — APPROVED** [review]
LGTM

**Comment by karlhaworth** [comment]
@nuritizra one conflict to address here

**Comment by karlhaworth** [comment]
@nuritizra one failing test

**Review by karlhaworth — DISMISSED** [review]

**Comment by nuritizra** [comment]
@karlhaworth thanks for approving, how might this PR get merged?

**Comment by vanessap-aa** [comment]
> @karlhaworth thanks for approving, how might this PR get merged?

The roadie team needs to approve and merge.

**Comment by nuritizra** [comment]
> > @karlhaworth thanks for approving, how might this PR get merged?
> 
> The roadie team needs to approve and merge.

How do I ping them here?

**Comment by karlhaworth** [comment]
> > > @karlhaworth thanks for approving, how might this PR get merged?
> > 
> > 
> > The roadie team needs to approve and merge.
> 
> How do I ping them here?

it looks like they use a private team. Sometimes I reach them on discord if needed. 

@punkle are you able to assist so we don't incur more conflicts?

**Review by punkle — APPROVED** [review]

**Pull request merged**
