### PR TITLE
Bumped a few dependencies and updating to use later `material-ui`

### PR DESCRIPTION
**Pull request by benjdlambert**
I think some peoples `yarn backstage-cli versions:bump` is failing due to some roadie dependencies being out of date, so I've tried to update things to latest version :)

### CODE REVIEW

**Comment by Xantier** [comment]
Thanks @benjdlambert, this is a duplicate oh #89 which is running through the CI pipeline now and will be merged in a bit.

**Comment by benjdlambert** [comment]
Ah ok - sorry - should have checked first :)

**Comment by teppichKay** [comment]
@benjdlambert Hey I think your PR isn't a fully duplicate one with #89 (see my comments there)

**Comment by benjdlambert** [comment]
@teppichKay I think that the end result should still be the same, as it won't bring in two versions if they match the same semver, you can see that the `yarn.lock` did bring in the correct version without the change. I just did it as a backup, but it should probably for consistency be changed too

**Comment by teppichKay** [comment]
yeah you're right. Thanks!

**Pull request closed without merging**
