### PR TITLE
changeset changes for releasing bitbucket pullrequets plugin

### PR DESCRIPTION
**Pull request by smymoon**
#### :heavy_check_mark: Checklist

- [ ] Added tests for new functionality and regression tests for bug fixes
- [x] Added changeset (run `yarn changeset` in the root)
- [ ] Screenshots of before and after attached (for UI changes)
- [ ] Added or updated documentation (if applicable)

### CODE REVIEW

**Comment by smymoon** [comment]
@Xantier , want to release our changes for bitbucket pullrequest. for that, created this pr, you can please release my changes.

**Review by Xantier — APPROVED** [review]

**Comment by smymoon** [comment]
@Xantier still, am not able to get this plugin in local. got below error
`Error: Couldn't find package "@roadiehq/backstage-plugin-bitbucket-pullrequest" on the "npm" registry.`
if i miss anything?

**Comment by Xantier** [comment]
@smymoon the package was marked private in `package.json` and thus was not releasing by the workflow. I've published it now manually and it should be available in the registries

**Comment by smymoon** [comment]
@Xantier , thanks.

**Comment by smymoon** [comment]
@Xantier I 've installed bitbucket plugin package in local. and am trying to call the particular entity, but its through module not found error. I think, that particular plugin not released properly. Below you can see the packages npm module, it does n't have actual code.

error

Could you Please help me to fix this. pls

**Pull request merged**
