### PR TITLE
fix the issue https://github.com/RoadieHQ/roadie-backstage-plugins/issues/1464

### PR DESCRIPTION
**Pull request by RaoJackie123**
Date: Wed, 10 July 2024 13:36:39 -0500
Subject: [PATCH] Update the token for http:backstage:request action

This PR is to fix the issue https://github.com/RoadieHQ/roadie-backstage-plugins/issues/1464
The token logic should be replaced by the new auth method.

### CODE REVIEW

**Review by Xantier — APPROVED** [review]
Thanks!

**Comment by Xantier** [comment]
@RaoJackie123 CI pipeline looks to be red on this. If you could fix those issues, we can then merge and release

**Comment by RaoJackie123** [comment]
> @RaoJackie123 CI pipeline looks to be red on this. If you could fix those issues, we can then merge and release

Sure, I will fix them, thanks

**Comment by RaoJackie123** [comment]
> @RaoJackie123 CI pipeline looks to be red on this. If you could fix those issues, we can then merge and release

Hi @Xantier Could you please re-run the CI job? I think the build issue should be solved now. Thanks

**Comment by Xantier** [comment]
> By the way, may I know how to test the CI in my local side? to avoid any unexpected issue in CI

The commands run on CI are listed on the GitHub workflow file. You could probably run that string of commands locally to imitate the same run the CI is doing

**Comment by RaoJackie123** [comment]
> > By the way, may I know how to test the CI in my local side? to avoid any unexpected issue in CI
> 
> The commands run on CI are listed on the GitHub workflow file. You could probably run that string of commands locally to imitate the same run the CI is doing

Thanks, I noticed that it has some warning in prettier checking. I thought only error is not allowed, the warning is also not allowed, right?

**Comment by RaoJackie123** [comment]
> > > By the way, may I know how to test the CI in my local side? to avoid any unexpected issue in CI
> > 
> > 
> > The commands run on CI are listed on the GitHub workflow file. You could probably run that string of commands locally to imitate the same run the CI is doing
> 
> Thanks, I noticed that it has some warning in prettier checking. I thought only error is not allowed, the warning is also not allowed, right?

anyway, I will fix the prettier issue then.

**Comment by RaoJackie123** [comment]
> > By the way, may I know how to test the CI in my local side? to avoid any unexpected issue in CI
> 
> The commands run on CI are listed on the GitHub workflow file. You could probably run that string of commands locally to imitate the same run the CI is doing
Hi @Xantier I fixed the prettier issue, could you please re-run the CI job? it should work well now. Sorry for bothering you again and again. Thanks for your kind help.

**Comment by RaoJackie123** [comment]
> > > By the way, may I know how to test the CI in my local side? to avoid any unexpected issue in CI
> > 
> > 
> > The commands run on CI are listed on the GitHub workflow file. You could probably run that string of commands locally to imitate the same run the CI is doing
> > Hi @Xantier I fixed the prettier issue, could you please re-run the CI job? it should work well now. Sorry for bothering you again and again. Thanks for your kind help.

Hi @Xantier The last CI job failed due to the backend-test-utils version in the plugin package is different with the yarn lock file. I've changed the package version, could you please re-run the ci job? sorry for the back and forth.

**Comment by RaoJackie123** [comment]
Hi @Xantier Looks like the CI job failed due to below error:
image
I use the backend-test-utils package in the test script, and also provide the package version in the package.json file under the plugin. But in the CI job, it told some dependency for the backend-test-utils package is not found, do you have any clue or suggestion on this error? Not sure where I forgot to config...

**Comment by RaoJackie123** [comment]
> Hi @Xantier Looks like the CI job failed due to below error: image I use the backend-test-utils package in the test script, and also provide the package version in the package.json file under the plugin. But in the CI job, it told some dependency for the backend-test-utils package is not found, do you have any clue or suggestion on this error? Not sure where I forgot to config...

image
The backend-test-utils package is installed under the install dependency stage. It should work, however, it's not.

**Comment by RaoJackie123** [comment]
Raised an issue in backstage for this: https://github.com/backstage/backstage/issues/26341

**Comment by RaoJackie123** [comment]
Hi @Xantier could you please re-run the CI job? I removed the dependency for backend-test-utils package to make sure the test case can be pass.

**Comment by RaoJackie123** [comment]
> Hi @Xantier could you please re-run the CI job? I removed the dependency for backend-test-utils package to make sure the test case can be pass.

Hi @Xantier, could you please help run the CI job? Thanks a lot.

**Comment by RaoJackie123** [comment]
@kissmikijr @Xantier Hi team, could you please help run the ci job to check if all issues have been fixed? it runs well in my local. Thanks a lot.

**Comment by RaoJackie123** [comment]
> @kissmikijr @Xantier Hi team, could you please help run the ci job to check if all issues have been fixed? it runs well in my local. Thanks a lot.

Hi @kissmikijr @Xantier @Irma12, looks like the ci job is good, could you please help review and approve this PR? 
This is to fix the issue https://github.com/RoadieHQ/roadie-backstage-plugins/issues/1464
the action http:backstage:request is not compatible with the latest version of backstage, so I did some minor change based on the backstage contributor's suggestion. Thanks a lot for your kind help.

**Review by kissmikijr — CHANGES_REQUESTED** [review]
Can you add a changeset please?

**Comment by RaoJackie123** [comment]
> Can you add a changeset please?

Hi @kissmikijr I added the changeset, could you please re-run the CI job and approve this PR? Thanks a lot for your kind help.

**Comment by RaoJackie123** [comment]
> > Can you add a changeset please?
> 
> Hi @kissmikijr I added the changeset, could you please re-run the CI job and approve this PR? Thanks a lot for your kind help.

@kissmikijr Just pull the latest version of main branch, could you please review again?

**Comment by RaoJackie123** [comment]
Hi @Xantier @kissmikijr Could you please review this PR? Thanks

**Review by kissmikijr — APPROVED** [review]

**Comment by RaoJackie123** [comment]
Hi @Xantier @kissmikijr Looks like I'm not able to merge this PR, could you please help to merge it?

**Pull request merged**
