### PR TITLE
Update new FE system default filters for datadog

### PR DESCRIPTION
**Pull request by alex-mckay**
Updates the default filter within Datadog's new FE system components to use the entity filter function used elsewhere. This means the content (cards & tab) will only appear on entities that have the relevant required annotation. Also updates the documentation to remove references to the app-config, since the FE system now auto-discovers entity content. 

#### :heavy_check_mark: Checklist

- [ ] Added tests for new functionality and regression tests for bug fixes
- [X] Added changeset (run `yarn changeset` in the root)
- [ ] Screenshots of before and after attached (for UI changes)
- [X] Added or updated documentation (if applicable)

### CODE REVIEW

**Comment by alex-mckay** [comment]
Hmm looks like the e2e test might be flaky / failing on yarn install even though that step passed before rebase & there are no packages changes in this PR. @punkle I see you doing some other work on main, any change you can retrigger the CI step here?

**Comment by punkle** [comment]
@alex-mckay the rerun seems to have worked?

**Comment by alex-mckay** [comment]
@punkle it did! Last time I contributed I think re-runs weren't automatic/needed someone from Roadie to kick off, but either way it's sorted now. Any way you can review? Otherwise can ask @Xantier who did previous Datadog reviews - but this change is quite small

**Comment by alex-mckay** [comment]
Hey @Xantier, looking for a review here whenever you have time ☺️

**Review by Xantier — APPROVED** [review]

**Pull request merged**
