### PR TITLE
@roadiehq/scaffolder-backend-module-http-request: Allow specifying absolute Urls in the Path 

### PR DESCRIPTION
**Pull request by ewassef**
This will allow the callers to specify absolute paths as well as relative ones

#### :heavy_check_mark: Checklist

- [ x] Added tests for new functionality and regression tests for bug fixes
- [ ] Screenshots of before and after attached (for UI changes)
- [ ] Added or updated documentation (if applicable)

### CODE REVIEW

**Comment by ewassef** [comment]
@kissmikijr I noticed you were one of the latest committers

**Comment by punkle** [comment]
@Xantier apologies, just seeing your comment now after posting mine.

**Comment by ewassef** [comment]
> Hi @ewassef ,
> 
> Thanks for the contribution! I think this was one of the functionalities that was originally in the action already but we backed out from because it introduces a security hole without much possibilities to mitigate the blast radius. Having the URLs and calls be backed by Backstage will give admins the possibility to use Backstage configs to expose only few known URLs.
> 
> We could possible explore some ways to make this an optional functionality for users that necessary want to run this unsecurely, maybe via some configuration options.

Thank you for the reply. Can you give me some more details on the security issues it exposes? 
We will be attaching a sidecar to the backend written in .net to expose some business functionality. 
We explored creating a backend-plugin that was a simple proxy but this seemed to be a better option.

Are there any possible options that you are referring to that I can implement and contribute?

**Comment by Xantier** [comment]
> Are there any possible options that you are referring to that I can implement and contribute?

You could possibly create a [proxy configuration](https://backstage.io/docs/plugins/proxying#docsNav) in your Backstage instance that proxies the traffic to the sidecar service. It is usually better to do it this way, since Backstage configurations are more strictly guarded and managed by a dedicated team that administers Backstage whereas scaffolder templates etc. could possibly be done by anyone in the company.

**Comment by ewassef** [comment]
@Xantier that makes much more sense! I think this part was missed in our reading of the docs.. ill close this PR and use that instead.

**Pull request closed without merging**
