### PR TITLE
allow customization of the scaffolder action names

### PR DESCRIPTION
**Pull request by punkle**
allow customization of the scaffolder action names

#### :heavy_check_mark: Checklist

- [ ] Added tests for new functionality and regression tests for bug fixes
- [ ] Added changeset (run `yarn changeset` in the root)
- [ ] Screenshots of before and after attached (for UI changes)
- [ ] Added or updated documentation (if applicable)

### CODE REVIEW

**Comment by sblausten** [comment]
Sorry I don't have context on this either - what problem is it solving?

**Comment by iain-b** [comment]
While generally I like the idea of flexibility perhaps we should just have generic names? allowing customization means that templates using these actions won't necessarily be compatible across installations and I think that's something we'd want to consider carefully before proceeding.

**Comment by punkle** [comment]
@iain-b Im kinda worried that we might break someone who is already using these tasks.. maybe I can change their names and release a major version?

**Comment by punkle** [comment]
@sblausten The current names for the scaffolder actions contain `roadiehq:utils` before the action name. There are no other scaffolder tasks that follow this naming pattern. This patch set provides the ability for someone to select the name of the task step to use. It does this in a way that does not break compatability.

**Pull request closed without merging**
